src/harmonia/qml/AppTopBar.qml
src/harmonia/qml/DetailPage.qml
src/harmonia/qml/DownloadsPage.qml
src/harmonia/qml/ExpandedPlayer.qml
src/harmonia/qml/ExplorePage.qml
src/harmonia/qml/HistoryPage.qml
src/harmonia/qml/HomePage.qml
src/harmonia/qml/InsightsPage.qml
src/harmonia/qml/IntegrationsSettings.qml
src/harmonia/qml/LibraryPage.qml
src/harmonia/qml/LoginDialog.qml
src/harmonia/qml/LyricsPanel.qml
src/harmonia/qml/LyricsView.qml
src/harmonia/qml/Main.qml
src/harmonia/qml/MediaShelf.qml
src/harmonia/qml/NavigationSidebar.qml
src/harmonia/qml/PlayerBar.qml
src/harmonia/qml/QueuePanel.qml
src/harmonia/qml/SearchPage.qml
src/harmonia/qml/SettingsPage.qml
src/harmonia/qml/SongShelf.qml
src/harmonia/qml/VideoSurface.qml
